make all: churn casos freq

churn:
	@ PYTHONDONTWRITEBYTECODE=1 python3 teste_churn.py

casos:
	@ PYTHONDONTWRITEBYTECODE=1 python3 teste_casos.py

freq:
	@ PYTHONDONTWRITEBYTECODE=1 python3 frequencia.py